# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rFddTn3JOmxlworDrcmOeVb4A6BS_iwL
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py


import streamlit as st
from PIL import Image
import numpy as np
import tensorflow as tf


from ultralytics import YOLO


st.title("Waste Segregation Web")
st.write("Upload an image to get predictions.")


!gdown --id 1OsAa-MryW-4lNvzweL2xxw2qjn4yyUk4

model = YOLO("/content/best.pt")

file = st.file_uploader("Choose an image...", type=["jpg", "png", "jpeg", "webp"])

if file is not None:
    image = Image.open(file)
    st.image(image, caption='Uploaded Image', use_column_width=True)
    st.write("")
    st.write("Classifying...")

    # Preprocess the image for your model
    image = image.resize((224, 224))  # Adjust size as per your model's requirement
    img_array = np.array(image) / 255.0  # Normalize if required
    img_array = np.expand_dims(img_array, axis=0)

    predictions = model.predict(img_array)
    st.write(predictions)  # Display predictions


!streamlit run app.py